New page: color modules example
mdn/css-examples pull request #125
Opened 2023-03-15 09:44 UTC by estelle

Example for new CSS color module page.

2023-03-15 16:15 UTC, teoli2003 requested changes
Made a first pass. We also need to run Prettify on this file; I'll do a last pass afterward (it is difficult to read like this).

Unless you know why, you should always use `===` instead of `==` and `textContent` instead of `innerHTML` if there is no HTML involve.

2023-03-15 16:15 UTC, teoli2003 commented on modules/colors.html
> +    h += 360;
```suggestion
  if ( delta === 0 ) {
    h = 0;
  } else if ( cmax === r ) {
    h = (( g - b ) / delta ) % 6;
  } else if ( cmax === g ) {
    h = ( b - r ) / delta + 2;
  } else {
    h = ( r - g ) / delta + 4;
  }
  
  h = Math.round( h * 60 );

  if ( h < 0 ) {
    h += 360;
  }
```

2023-03-15 16:15 UTC, teoli2003 commented on modules/colors.html
> +  }
```suggestion
  if( opacity === 1 ) {
    cell.textContent = `hwb(${h} ${W.toFixed( 1 )}% ${B.toFixed( 1 )}%)`;
  }
  else {
    cell.textContent = `hwb(${h} ${W.toFixed( 1 )}% ${B.toFixed( 1 )}% / ${opacity})`;
  }
```

2023-03-15 16:15 UTC, teoli2003 commented on modules/colors.html
> +const setBackgroundColor = function ( color, opacity ) {
```suggestion
function setBackgroundColor( color, opacity ) {
```

2023-03-15 16:15 UTC, teoli2003 commented on modules/colors.html
> +  if( opacity == 1 ) {
```suggestion
  if( opacity === 1 ) {
```

2023-03-15 16:15 UTC, teoli2003 commented on modules/colors.html
> +    body.style.backgroundColor = color + "" + hexOpacity( opacity );
```suggestion
    body.style.backgroundColor = `${color}${hexOpacity(opacity)}`;
```

2023-03-15 16:15 UTC, teoli2003 commented on modules/colors.html
> +const hexOpacity = function( opacity ) {
```suggestion
function hexOpacity( opacity ) {
```

2023-03-16 17:25 UTC, estelle commented on modules/colors.html
> +          color = color + "" + hexOpacity(opacity);
```suggestion
          color = `${color}${hexOpacity(opacity)}`;
```

2023-03-16 17:49 UTC, estelle commented
@teoli2003 We went with 

```javascript
function hexOpacity(color, opacity)  {
  let char = "00";
  if (opacity > 0) {
    char = Math.floor(opacity * 255).toString(16);
  }
  return `${color}${char}`;
}
```

Is it also ok to go with the following way of declaring a function (the first line), or against our best practices guidelines?

```javascript
const hexOpacity = (color, opacity) => {
  let char = "00";
  if (opacity > 0) {
    char = Math.floor(opacity * 255).toString(16);
  }
  return `${color}${char}`;
}
```

2023-03-17 09:19 UTC, teoli2003 requested changes
There are a few last small changes, but I find this much easier to read already!

2023-03-17 09:19 UTC, teoli2003 commented on modules/colors.html
> +        const currentOpacity = opacityPicker.value * 1;
See https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Writing_style_guide/Code_style_guide/JavaScript#type_coercion
```suggestion
        const currentOpacity = Number(opacityPicker.value);
```

2023-03-17 09:19 UTC, teoli2003 commented on modules/colors.html
> +        (r = r / 255), (g = g / 255), (b = b / 255);
This is difficult to read.
```suggestion
        // Let's have r, g, b in the range [0, 1]
        r = r / 255;
        g = g / 255;
        b = b / 255;
```

2023-03-17 09:19 UTC, teoli2003 commented on modules/colors.html
> +        else h = (r - g) / delta + 4;
According our guidelines:
```suggestion
        if (delta === 0) {
          h = 0;
        } else if (cmax === r) {
          h = ((g - b) / delta) % 6;
        } else if (cmax === g) {
          h = (b - r) / delta + 2;
        }
        else h = (r - g) / delta + 4;
```

2023-03-17 09:19 UTC, teoli2003 commented on modules/colors.html
> +        if (h < 0) h += 360;
```suggestion
        // We want an angle between 0 and 360°
        if (h < 0) {
          h += 360;
        }
```

2023-03-17 09:19 UTC, teoli2003 commented on modules/colors.html
> +        l = +(l * 100).toFixed(1);
If there is a risk that the result of toFixed() is not a number, we should convert it explicitely:
```suggestion
        s = Number((s * 100).toFixed(1));
        l = Number((l * 100).toFixed(1));
```

2023-03-17 09:19 UTC, teoli2003 commented on modules/colors.html
> +        }
I think this is easier to read:
```suggestion
        let W = (hsv === 0) ? 0 : ((2 * hsv) / (l + hsv)) * 100;
        let B = l + hsv;
        W = W.toFixed(1);
        B = B.toFixed(1);
        if (opacity === 1) {
          cell.textContent = `hwb(${h} ${W}% ${B}%)`;
        } else {
          cell.textContent = `hwb(${h} ${W}% ${B}% / ${opacity})`;
        }
```

2023-03-17 09:22 UTC, teoli2003 commented
> @teoli2003 We went with
> 
> ```js
> function hexOpacity(color, opacity)  {
>   let char = "00";
>   if (opacity > 0) {
>     char = Math.floor(opacity * 255).toString(16);
>   }
>   return `${color}${char}`;
> }
> ```
> 
> Is it also ok to go with the following way of declaring a function (the first line), or against our best practices guidelines?
> 
> ```js
> const hexOpacity = (color, opacity) => {
>   let char = "00";
>   if (opacity > 0) {
>     char = Math.floor(opacity * 255).toString(16);
>   }
>   return `${color}${char}`;
> }
> ```

When possible, I prefer to have a `function` definition. I don't see what the longest syntax brings to readability.

(I'm not a fan of setting the else value before the if, but that's not against our rules and a matter of taste)

2023-03-18 05:29 UTC, teoli2003 approved these changes
👍

2023-03-18 05:29 UTC, merged