add cross browser support for image-set() css ref in alternative image formats example
mdn/css-examples pull request #50
Opened 2021-09-13 05:18 UTC by digi-booster

…e formats example

2021-09-13 05:24 UTC, digi-booster commented
@teoli2003 Can you review this?

2021-09-13 06:00 UTC, rachelandrew requested changes
You need to repeat any change inside the textarea or it will be overwritten onload. 

These are very easy to test by opening them in a browser.

2021-09-13 08:13 UTC, digi-booster commented
> You need to repeat any change inside the textarea or it will be overwritten onload.
> 
> These are very easy to test by opening them in a browser.

Is this correct now?

2021-09-23 12:26 UTC, digi-booster commented
Hi @rachelandrew, I waiting for your re-review of this pr.

2021-09-25 06:57 UTC, rachelandrew commented
To open a file in a browser? Double click the file icon, it will open in the browser.

2021-09-25 06:59 UTC, rachelandrew commented on images/image-set-type.html
>      <textarea class="playable playable-css" style="height: 150px;">
Have you tested that this does not cause a scrollbar? I think height: 150px will not be tall enough for people to see the code.

2021-09-25 08:13 UTC, digi-booster commented on images/image-set-type.html
>      <textarea class="playable playable-css" style="height: 150px;">
```suggestion
    <textarea class="playable playable-css" style="height: 155px;">
```
height: 150px;
![before](https://user-images.githubusercontent.com/74658643/134764332-792fe712-0e0a-4c3a-bff2-e7f02e0a8050.png)

height: 155px;
![after](https://user-images.githubusercontent.com/74658643/134764386-49da1a89-e707-4dfb-9306-d094af34ea2d.png)

2021-09-28 14:27 UTC, rachelandrew approved these changes

2021-09-28 14:27 UTC, merged